#!/usr/bin/env zsh
DIR=${0:a:h}

set -e

mkdir -p ~/.config
mkdir -p ~/.local/share

ln -sf $DIR/zshrc ~/.zshrc
ln -sf $DIR/zprofile ~/.zprofile
ln -sf $DIR/gitignore ~/.gitignore

if [[ ! "$(hostname)" =~ "(.*)\.amazon\.com$" ]]; then
    ln -sf $DIR/gitconfig ~/.gitconfig
fi
