#!/usr/bin/env zsh
DIR=${0:a:h}

set -e

ln -sf $DIR/sh/zshrc ~/.zshrc
ln -sf $DIR/scm/gitignore ~/.gitignore
ln -sf $DIR/scm/gitconfig ~/.gitconfig

mkdir -p ~/.config
ln -sf $DIR/nvim ~/.config/nvim

. ./setup_files/install_packages.zsh
. ./setup_files/install_dnf.zsh
. ./setup_files/install_npm.zsh
. ./setup_files/install_pip.zsh
. ./setup_files/install_luarocks.zsh
