#!/usr/bin/env zsh
DIR=${0:a:h}

set -e

mkdir -p ~/.config/sway
mkdir -p ~/.config/kitty
mkdir -p ~/.local/share

ln -sf $DIR/zshrc ~/.zshrc
ln -sf $DIR/zprofile ~/.zprofile
ln -sf $DIR/gitignore ~/.gitignore
ln -sf $DIR/config/nvim ~/.config/
ln -sf $DIR/local/share/nvim ~/.local/share/
ln -sf $DIR/sway_config ~/.config/sway/config
ln -sf $DIR/kitty.conf ~/.config/kitty/kitty.conf

if [[ ! "$(hostname)" =~ "(.*)\.amazon\.com$" ]]; then
    ln -sf $DIR/gitconfig ~/.gitconfig
fi
